version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lamguin"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-v7husqqlc48f"
s3_prefix = "lamguin"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

