AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lamguin

  Sample SAM Template for lamguin

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  FeedPenguinsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: feed_penguins/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        List:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /list
            Method: get
        AttemptCharge:
          Type: Api
          Properties:
            Path: /attempt_charge
            Method: post

Outputs:
  FeedPenguinsApi:
    Description: "API Gateway endpoint URL for Prod stage for Feed Penguins function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/feed_penguins/"
  FeedPenguinsFunction:
    Description: "Feed Penguins Lambda Function ARN"
    Value: !GetAtt FeedPenguinsFunction.Arn
  FeedPenguinsFunctionRole:
    Description: "Implicit IAM Role created for Feed Penguins function"
    Value: !GetAtt FeedPenguinsFunctionRole.Arn
